services:
  - type: web
    name: notes-app-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://gnanavardhini2_db_user:gnanavardhini@internshalassignment.ed9vdpa.mongodb.net/?retryWrites=true&w=majority&appName=Internshalassignment
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

  - type: web
    name: notes-app-frontend
    env: static
    buildCommand: chmod +x build-frontend.sh && ./build-frontend.sh
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: notes-app-backend
          property: host
# databases:
  # - name: notes-app-db
  #   plan: free

